abb_irb:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  type: "effort_controllers/JointTrajectoryController"
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

  constraints:
    goal_time: 1                   # Override default
    joint_1:
      goal: 0.1                     # Not enforced if unspecified
    joint_2:
      goal: 0.1                      # Not enforced if unspecified
    joint_3:
      goal: 0.1                      # Not enforced if unspecified
    joint_4:
      goal: 0.1                      # Not enforced if unspecified
    joint_5:
      goal: 0.1                      # Not enforced if unspecified
    joint_6:
      goal: 0.1                      # Not enforced if unspecified

  gains: # Required because we're controlling an effort interface
    joint_1: {p: 10000.0, i: 1, d: 500}
    joint_2: {p: 10000.0, i: 1, d: 500}
    joint_3: {p: 10000.0, i: 1, d: 500}
    joint_4: {p: 10000.0, i: 1, d: 500}
    joint_5: {p: 10000.0, i: 1, d: 500}
    joint_6: {p: 10000.0, i: 1, d: 500}
